### PR TITLE
Modernize ac_find_gap.m4

### PR DESCRIPTION
**Pull request by fingolfin**
* drop CONFIGNAME support
* make it possible to compile against future GAP releases with
  compatibility mode turned off

### CODE REVIEW

**Comment by fingolfin** [comment]
BTW I based this on stable-3.0, so if you prefer this PR there, it's trivial change the target branch.

**Comment by james-d-mitchell** [comment]
Thanks for this too @fingolfin, can you please rebase it onto `stable-3.0`?

**Comment by fingolfin** [comment]
@james-d-mitchell done (I see there is also a stable-3.1 branch, but since you told me to target stable-3.0, that's what I did).

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin that's all good.

**Pull request merged**
