### PR TITLE
Install selective Size methods for monogenic semigroups

### PR DESCRIPTION
**Pull request by wilfwilson**
Previously all monogenic semigroups which knew their minimal
generating set would use IndexPeriod to calculate their size.
For generic semigroup elements, IndexPeriod would then have to
recreate the monogenic semigroup, enumerate it, and hence deduce
its size - and then do even more work. This method is now only used
for elements which have a better IndexPeriod method.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Looks good except that the convention used elsewhere in the package is to name a function which will be deleted/unbound after being used in an `InstallMethod` starting with an underscore. 

Also I installed a method for `IsFinite` in PR #212, so you could remove that from the tests.

**Comment by james-d-mitchell** [comment]
Sorry, the convention is to call the function `_SemigroupSizeByIndexPeriod`, i.e. without the prefix `SEMIGROUPS`, please revise.

**Comment by wilfwilson** [comment]
@james-d-mitchell no worries, I've sorted the naming out now.

**Comment by james-d-mitchell** [comment]
Looks great!

**Pull request merged**
