### PR TITLE
Add methods for IsTorsion, Order, and InverseOp for integer matrices

### PR DESCRIPTION
**Pull request by james-d-mitchell**
and some tests.

### CODE REVIEW

**Comment by wilfwilson** [comment]
I think the new `IsTorsion` method should be documented. I'm happy with everything else.

**Comment by james-d-mitchell** [comment]
@wilfwilson agreed, I think that Stuart documented in his PR, I am waiting for Stuart to comment on this before doing anything else, since I found the code here in a branch on my repo, I think Stuart and I worked on this at some point in the past, and I wanted to make sure it made it into 3.0.0

**Comment by wilfwilson** [comment]
@james-d-mitchell Yep, he has got documentation in his PR.

**Comment by stuartburrell** [comment]
I've had a look at everything, looks great to me.

About the doc for IsTorsion - in my PR there is only doc for max-plus IsTorsion, not integer matrices. Shall I add some in? Although I guess that would make more sense in this PR, so I can write and send to James for this PR if better.

**Comment by james-d-mitchell** [comment]
Thanks Stuart! If you could just add the doc in your PR that will be ok. Thanks alot!

**Comment by stuartburrell** [comment]
I need to merge this PR into my branch before my PR will pass Travis CI with new doc. Is this ready to go into unstable 3-0?

**Comment by james-d-mitchell** [comment]
Yup, ready to go, and merged!

**Pull request merged**
