### PR TITLE
Fix bug in IsRowTrim / IsColTrim for boolean matrices

### PR DESCRIPTION
**Pull request by flsmith**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Thanks @flsmith looks like you might have forgotten to update the manual examples though.

**Comment by james-d-mitchell** [comment]
@flsmith and linting it the last thing!

**Comment by james-d-mitchell** [comment]
Also please rebase onto stable-3.2

**Comment by flsmith** [comment]
Fixed up in #654.

**Pull request closed without merging**
