### PR TITLE
travis: configure with --with-external-libsemigroups

### PR DESCRIPTION
**Pull request by james-d-mitchell**
In this PR I add a travis test for when Semigroups is configured with the flag `--with-external-libsemigroups`.

### CODE REVIEW

**Comment by dimpase** [comment]
Just in case: is conda playing with `pkg-config` right? I.e., to me there is no guarantee that the config of libsemigroup lands in the place where pkg-config picks it up without an extra parameter, as I describe here: https://github.com/james-d-mitchell/libsemigroups/pull/113 (I'm not a conda user, so perhaps my suspicion here is misplaced).

**Comment by james-d-mitchell** [comment]
I'm going to close this for now.

**Comment by dimpase** [comment]
Have you got it working?

**Comment by james-d-mitchell** [comment]
Yes, in PR #593, there were various complications including the one you mentioned.

**Pull request closed without merging**
