### PR TITLE
Use SET_ELM_BLIST only when available, else use SET_BIT_BLIST

### PR DESCRIPTION
**Pull request by fingolfin**
This is required for https://github.com/gap-system/gap/pull/1871

Also, don't bother setting 0 bits, as a fresh blist is guaranteed to zeroed.

### CODE REVIEW

**Comment by wilfwilson** [comment]
Thanks for this @fingolfin. Semigroups already requires GAP 4.9, so we won't need the `#ifdef`. Once https://github.com/gap-system/gap/pull/1871 is merged we'll sort it out :)

**Comment by fingolfin** [comment]
@wilfwilson the problem with that is that it'll lead to our `testpackages` tests failing on Travis. So this is a classical chicken-and-egg. If I am to merge that PR now, then I'd first have to augment it to somehow disable or ignore the semigroups failures.

**Comment by james-d-mitchell** [comment]
@fingolfin I'm happy with this as it is, we can always remove the `#ifdef` later.

Is travis failing because this PR depends on gap-system/gap#1871?

**Comment by wilfwilson** [comment]
We'll want this in the `stable-3.0` branch @james-d-mitchell, since I suppose you'll be making a minor release from there.

This shouldn't fail travis because of https://github.com/gap-system/gap/pull/1871, thanks to the `#ifdef`. I think it's something to do with us using the released IO 4.4.4 in some of our Travis jobs, but I'll investigate.

**Comment by fingolfin** [comment]
I'll make that release today. Sorry for the inconvenience

**Comment by wilfwilson** [comment]
No worries @fingolfin.

**Comment by wilfwilson** [comment]
@fingolfin I'm going to cherry-pick this onto `stable-3.0` and close this PR, to save you the time of changing the PR.

(For future reference, we use `stable-3.0` for bugfixes/compatibility changes, and for making minor releases. `stable-3.0` gets merged into `master` very frequently. `master` is where we put new features and more major changes.)

We (aka @james-d-mitchell) will release Semigroups 3.0.9 once you make an IO release (we will be requiring that release once it is made).

**Comment by fingolfin** [comment]
Thanks @wilfwilson. I am sorry I keep forgetting about branches; I don't mind changing the PR next time, though, and I'll try to remember.

The IO release has been delayed as we run into regressions, but I hope we really can release it today *fingers crossed*

**Comment by fingolfin** [comment]
FYI, io 4.5.0 has been released and picked up for redistribution.

**Comment by james-d-mitchell** [comment]
Will probably make a release tomorrow, thanks @fingolfin

**Pull request closed without merging**
