### PR TITLE
Libsemigroups 1.0.0

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This PR updates Semigroups to use the not yet released v1.0.0 of libsemigroups. I expect the tests to fail at this point, just making this for reference at present.

### CODE REVIEW

**Comment by wilfwilson** [comment]
What's going on with this? I noticed that libsemigroups 1.0.1 and 1.0.0 were released.

**Comment by james-d-mitchell** [comment]
I’m going to make a release of Semigroups with Libsemigroups 1.0.0 on Monday :)

**Comment by wilfwilson** [comment]
Great!

**Comment by wilfwilson** [comment]
Almost there! Just the linting job is failing now:

https://travis-ci.org/gap-packages/Semigroups/jobs/619641066

**Pull request merged**
