### PR TITLE
Digraphs v1.0

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This PR updates Semigroups to work with the new version of Digraphs, i.e. the stuff in

https://github.com/gap-packages/Digraphs/pull/171

### CODE REVIEW

**Comment by wilfwilson** [comment]
This will ideally require Digraphs and Semigroups to be released as closed to each other as possible, as otherwise the existing version of Semigroups will not work with the latest version of Digraphs, that is, `v1.0`.

This PR will also need to update the required version of Digraphs to `1.0`. Until this is done, and Digraphs 1.0 is released, the CI on this PR will fail.

**Comment by wilfwilson** [comment]
My changes to the view strings for Digraphs mean that this needs updating again. But it may as well wait until changes to Digraphs have finished completely

**Comment by wilfwilson** [comment]
Mostly a TODO: `CanonicalBlocks` might have a different output with Digraphs 1.0. Presumably harmless, but the new result should be checked for correctness before we make the change in the test file.
```
gap> Test("tst/standard/blocks.tst");
########> Diff in tst/standard/blocks.tst:150
# Input is:
CanonicalBlocks(blocks);
# Expected output:
<blocks: [ 1*, 2*, 3*, 4*, 5* ], [ 6*, 7*, 8*, 9*, 10* ], [ 11*, 12*, 13*, 14*\
 ], [ 15*, 16*, 17*, 18* ], [ 19*, 20* ]>
# But found:
<blocks: [ 1*, 2* ], [ 3*, 4*, 5*, 6* ], [ 7*, 8*, 9*, 10* ], [ 11*, 12*, 13*,\
 14*, 15* ], [ 16*, 17*, 18*, 19*, 20* ]>
########
########> Diff in tst/standard/blocks.tst:154
# Input is:
CanonicalBlocks(blocks);
# Expected output:
<blocks: [ 1, 2, 3, 4 ],
[ 5, 6, 7
 ], [ 8*, 9*, 10* ], [ 11*, 12*, 13* ], [ 14*, 15*, 16* ], [ 17*, 18* ], [ 19*\
, 20* ]>
# But found:
<blocks: [ 1*, 2* ], [ 3*, 4* ], [ 5*, 6*, 7* ], [ 8*, 9*, 10* ], [ 11*, 12*, \
13* ], [ 14, 15, 16 ], [ 17, 18, 19, 20 ]>
########
########> Diff in tst/standard/blocks.tst:159
# Input is:
Print(last); "this string allows us to test the PrintObj method";
# Expected output:
BlocksNC([ [ -1, -2, -3, -4 ], [ -5, -6, -7 ], [ 8, 9, 10 ], [ 11, 12, 13 ], [\
 14, 15, 16 ], [ 17, 18 ], [ 19, 20 ] ])"this string allows us to test the Pri\
ntObj method"
# But found:
BlocksNC([ [ 1, 2 ], [ 3, 4 ], [ 5, 6, 7 ], [ 8, 9, 10 ], [ 11, 12, 13 ], [ -1\
4, -15, -16 ], [ -17, -18, -19, -20 ] ])"this string allows us to test the Pri\
ntObj method"
########
Semigroups package: standard/blocks.tst
msecs: 9
false
```

**Comment by james-d-mitchell** [comment]
Merged @wilfwilson PR, and rebased on current master branch. Thanks @wilfwilson

**Comment by wilfwilson** [comment]
Thanks @james-d-mitchell, I'll fixed the remaining Travis problems with another PR to your branch.

**Pull request merged**
