### PR TITLE
Options

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This PR cleans up the processing of options records, so that it can be used more widely.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Any idea what's going wrong here? @wilfwilson ?

**Comment by wilfwilson** [comment]
Strange. It's 32-bit, with the newest version of the dependencies. This is our only 32-bit test. I would guess that it is caused by a recent change to GAP.

**Comment by james-d-mitchell** [comment]
I think hashing of permutations is messed up in GAP master,  I can reproduce the errors in 64 bit on my computer.

**Comment by james-d-mitchell** [comment]
The tests are failing because hashing of permutations is broken in Orb:

https://github.com/gap-packages/orb/pull/35

**Comment by wilfwilson** [comment]
If you rebase on `origin/stable-3.0`, hopefully the tests will now pass.

**Comment by james-d-mitchell** [comment]
Yup ready to go

**Pull request merged**
