### PR TITLE
Add a --enable-debug configure option and add warning if libsemigroups is not available 

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
This PR requires libsemigroups 0.5.1 (not yet released)

**Comment by james-d-mitchell** [comment]
libsemigroups 0.5.1 is out, and so this can be merged if the CI pass.

**Comment by wilfwilson** [comment]
Now that libsemigroups 0.5.1 is out, Travis will be using 0.5.1 and so the tests for all the pull requests that are open at the moment will fail until this is merged into stable-3.0, and stable-3.0 is merged into master.

I think we need to avoid this problem. Currently Travis selects the newest released version of libsemigroups, and uses that. Instead, I think we need to have a variable in the Travis setup, which specifies which version of libsemigroups to use. Then, when you release a new version of libsemigroups, you should make your usual pull request to make Semigroups compatible with the newest version of libsemigroups - and as part of that PR, you should update that token in the `.travis.yml` file to the newest version of libsemigroups.

Sound like a good idea?

**Comment by james-d-mitchell** [comment]
Yes, @wilfwilson this does sound like a good idea.

**Comment by james-d-mitchell** [comment]
This resolves Issue #353.

**Pull request merged**
