### PR TITLE
Update CONTRIBUTING and CHANGELOG for v3.1.0

### PR DESCRIPTION
**Pull request by wilfwilson**
This is a good start I think. Please merge and continue the work @james-d-mitchell because I don't have time for any more

### CODE REVIEW

**Comment by wilfwilson** [comment]
Not much.

In terms of information about bugs/new features/changes, I don't think there is anything else.

Main thing is the date, and a sentence/paragraph introduction.

And checking what I've written, if you want :)

**Comment by wilfwilson** [comment]
(I was in a rush to leave when I created the PR, hence the lack of detail :wink:)

**Comment by wilfwilson** [comment]
I think the `CHANGELOG` is good to go, and I've also slightly updated the `CONTRIBUTING` file to make it more accurate (I don't claim it is completely up to date, but it's better than what was there before).

**Comment by james-d-mitchell** [comment]
Thanks for this @wilfwilson sorry for the delay. If you approve PR #572, then I will release.

**Pull request merged**
