### PR TITLE
Release candidate for v3.0.18

### PR DESCRIPTION
**Pull request by james-d-mitchell**

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Uhoh looks like the travis set up is broken again @wilfwilson, any chance you could take a look:

https://travis-ci.org/gap-packages/Semigroups/builds/427179127?utm_source=github_status&utm_medium=notification

Fails with the error:
~~~~
Getting latest release of digraphs...
Downloading digraphs-, from URL:
https://github.com/gap-packages/digraphs/releases/download/v/digraphs-.tar.gz
~~~~

looks like it isn't finding the (correct, or any) version of digraphs.

**Comment by wilfwilson** [comment]
I'm hoping it's just a spurious failure on a single build, I've restarted the failed build.

**Comment by wilfwilson** [comment]
@james-d-mitchell Tests pass! It was just one sporadic failure. Let's hope that's not going to be a frequent occurrence.

**Comment by alex-konovalov** [comment]
Thanks - picked up for testing!
```
* Semigroups - new version 3.0.18 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/gap-packages/Semigroups/releases/download/v3.0.18/semigro\
ups-3.0.18[ ".tar.gz" ]
  unpacking semigroups-3.0.18.tar.gz
  Validation of the info file successful!
  Package Semigroups 3.0.18 from 11/09/2018 has dependencies:
  * NeededOtherPackages [ [ "orb", ">=4.8.0" ], [ "io", ">=4.5.1" ], 
  [ "digraphs", ">=0.12.0" ], [ "genss", ">=1.6.5" ] ]
  * GAP >=4.9.0
  * SuggestedOtherPackages [ [ "gapdoc", ">=1.5.1" ] ]
  finding text files  . . .

=====================text files==========================
semigroups-3.0.18/PackageInfo.g
semigroups-3.0.18/LICENSE
semigroups-3.0.18/README.md
semigroups-3.0.18/VERSION
semigroups-3.0.18/makedoc.g
semigroups-3.0.18/GPL
semigroups-3.0.18/init.g
semigroups-3.0.18/read.g
semigroups-3.0.18/gap/obsolete.gi
semigroups-3.0.18/gap/options.g
semigroups-3.0.18/gap/obsolete.gd
semigroups-3.0.18/gap/smallestimage.g
semigroups-3.0.18/gap/ideals/idealact.gi
semigroups-3.0.18/gap/ideals/ideallam.gi
semigroups-3.0.18/gap/ideals/ideals.gd
semigroups-3.0.18/gap/ideals/idealenum.gi
semigroups-3.0.18/gap/ideals/ideallam.gd
semigroups-3.0.18/gap/ideals/idealact.gd
semigroups-3.0.18/gap/ideals/ideals.gi
semigroups-3.0.18/gap/tools/iterators.gd
semigroups-3.0.18/gap/tools/enums.gi
semigroups-3.0.18/gap/tools/utils.gd
semigroups-3.0.18/gap/tools/display.gi
semigroups-3.0.18/gap/tools/io.gi
semigroups-3.0.18/gap/tools/iterators.gi
semigroups-3.0.18/gap/tools/utils.gi
semigroups-3.0.18/gap/tools/enums.gd
semigroups-3.0.18/gap/tools/display.gd
semigroups-3.0.18/gap/tools/io.gd
semigroups-3.0.18/gap/semigroups/semigrp.gd
semigroups-3.0.18/gap/semigroups/semiex.gi
semigroups-3.0.18/gap/semigroups/semiboolmat.gd
semigroups-3.0.18/gap/semigroups/semifp.gd
semigroups-3.0.18/gap/semigroups/semirms.gd
semigroups-3.0.18/gap/semigroups/semicons.gd
semigroups-3.0.18/gap/semigroups/semitrans.gi
semigroups-3.0.18/gap/semigroups/semiquo.gd
semigroups-3.0.18/gap/semigroups/semipbr.gd
semigroups-3.0.18/gap/semigroups/semiffmat.gd
semigroups-3.0.18/gap/semigroups/semigraph.gd
semigroups-3.0.18/gap/semigroups/semimaxplus.gd
semigroups-3.0.18/gap/semigroups/semiringmat.gd
semigroups-3.0.18/gap/semigroups/grpffmat.gi
semigroups-3.0.18/gap/semigroups/grpperm.gd
semigroups-3.0.18/gap/semigroups/semibipart.gi
semigroups-3.0.18/gap/semigroups/semipperm.gd
semigroups-3.0.18/gap/semigroups/semifp.gi
semigroups-3.0.18/gap/semigroups/semiboolmat.gi
semigroups-3.0.18/gap/semigroups/semiex.gd
semigroups-3.0.18/gap/semigroups/semigrp.gi
semigroups-3.0.18/gap/semigroups/semiquo.gi
semigroups-3.0.18/gap/semigroups/semitrans.gd
semigroups-3.0.18/gap/semigroups/semicons.gi
semigroups-3.0.18/gap/semigroups/semirms.gi
semigroups-3.0.18/gap/semigroups/semipbr.gi
semigroups-3.0.18/gap/semigroups/semibipart.gd
semigroups-3.0.18/gap/semigroups/grpperm.gi
semigroups-3.0.18/gap/semigroups/grpffmat.gd
semigroups-3.0.18/gap/semigroups/semiringmat.gi
semigroups-3.0.18/gap/semigroups/semimaxplus.gi
semigroups-3.0.18/gap/semigroups/semigraph.gi
semigroups-3.0.18/gap/semigroups/semiffmat.gi
semigroups-3.0.18/gap/semigroups/semipperm.gi
semigroups-3.0.18/gap/greens/gren.gd
semigroups-3.0.18/gap/greens/grac.gi
semigroups-3.0.18/gap/greens/gree.gd
semigroups-3.0.18/gap/greens/gracreg.gi
semigroups-3.0.18/gap/greens/grac.gd
semigroups-3.0.18/gap/greens/gren.gi
semigroups-3.0.18/gap/greens/gracinv.gi
semigroups-3.0.18/gap/greens/gree.gi
semigroups-3.0.18/gap/fp/freeinverse.gd
semigroups-3.0.18/gap/fp/freeband.gd
semigroups-3.0.18/gap/fp/freeinverse.gi
semigroups-3.0.18/gap/fp/freeband.gi
semigroups-3.0.18/gap/attributes/maximal.gd
semigroups-3.0.18/gap/attributes/properties.gi
semigroups-3.0.18/gap/attributes/factor.gd
semigroups-3.0.18/gap/attributes/attr.gd
semigroups-3.0.18/gap/attributes/attrinv.gi
semigroups-3.0.18/gap/attributes/normalizer.gd
semigroups-3.0.18/gap/attributes/isomorph.gd
semigroups-3.0.18/gap/attributes/attract.gd
semigroups-3.0.18/gap/attributes/isorms.gd
semigroups-3.0.18/gap/attributes/maximal.gi
semigroups-3.0.18/gap/attributes/factor.gi
semigroups-3.0.18/gap/attributes/properties.gd
semigroups-3.0.18/gap/attributes/attr.gi
semigroups-3.0.18/gap/attributes/attrinv.gd
semigroups-3.0.18/gap/attributes/normalizer.gi
semigroups-3.0.18/gap/attributes/isorms.gi
semigroups-3.0.18/gap/attributes/attract.gi
semigroups-3.0.18/gap/attributes/isomorph.gi
semigroups-3.0.18/gap/elements/boolmat.gi
semigroups-3.0.18/gap/elements/trans.gd
semigroups-3.0.18/gap/elements/maxplusmat.gd
semigroups-3.0.18/gap/elements/semiringmat.gd
semigroups-3.0.18/gap/elements/star.gi
semigroups-3.0.18/gap/elements/pperm.gi
semigroups-3.0.18/gap/elements/elements.gi
semigroups-3.0.18/gap/elements/pbr.gd
semigroups-3.0.18/gap/elements/bipart.gd
semigroups-3.0.18/gap/elements/blocks.gd
semigroups-3.0.18/gap/elements/ffmat.gi
semigroups-3.0.18/gap/elements/boolmat.gd
semigroups-3.0.18/gap/elements/trans.gi
semigroups-3.0.18/gap/elements/maxplusmat.gi
semigroups-3.0.18/gap/elements/star.gd
semigroups-3.0.18/gap/elements/semiringmat.gi
semigroups-3.0.18/gap/elements/bipart.gi
semigroups-3.0.18/gap/elements/pbr.gi
semigroups-3.0.18/gap/elements/elements.gd
semigroups-3.0.18/gap/elements/pperm.gd
semigroups-3.0.18/gap/elements/ffmat.gd
semigroups-3.0.18/gap/elements/blocks.gi
semigroups-3.0.18/gap/congruences/conguniv.gd
semigroups-3.0.18/gap/congruences/conginv.gd
semigroups-3.0.18/gap/congruences/cong.gi
semigroups-3.0.18/gap/congruences/conglatt.gi
semigroups-3.0.18/gap/congruences/congrms.gi
semigroups-3.0.18/gap/congruences/congpairs.gi
semigroups-3.0.18/gap/congruences/congfpmon.gd
semigroups-3.0.18/gap/congruences/congsimple.gi
semigroups-3.0.18/gap/congruences/congrees.gi
semigroups-3.0.18/gap/congruences/conguniv.gi
semigroups-3.0.18/gap/congruences/conginv.gi
semigroups-3.0.18/gap/congruences/cong.gd
semigroups-3.0.18/gap/congruences/congrms.gd
semigroups-3.0.18/gap/congruences/conglatt.gd
semigroups-3.0.18/gap/congruences/congsimple.gd
semigroups-3.0.18/gap/congruences/congfpmon.gi
semigroups-3.0.18/gap/congruences/congpairs.gd
semigroups-3.0.18/gap/congruences/congrees.gd
semigroups-3.0.18/gap/main/fropin.gi
semigroups-3.0.18/gap/main/setup.gd
semigroups-3.0.18/gap/main/lambda-rho.gi
semigroups-3.0.18/gap/main/orbits.gi
semigroups-3.0.18/gap/main/graded.gi
semigroups-3.0.18/gap/main/semiact.gd
semigroups-3.0.18/gap/main/acting.gd
semigroups-3.0.18/gap/main/fropin.gd
semigroups-3.0.18/gap/main/setup.gi
semigroups-3.0.18/gap/main/graded.gd
semigroups-3.0.18/gap/main/orbits.gd
semigroups-3.0.18/gap/main/lambda-rho.gd
semigroups-3.0.18/gap/main/semiact.gi
semigroups-3.0.18/gap/main/acting.gi
semigroups-3.0.18/doc/chap9_mj.html
semigroups-3.0.18/doc/blocks.xml
semigroups-3.0.18/doc/ffmat.xml
semigroups-3.0.18/doc/congrees.xml
semigroups-3.0.18/doc/semiex.xml
semigroups-3.0.18/doc/orbits.xml
semigroups-3.0.18/doc/grpperm.xml
semigroups-3.0.18/doc/chapBib_mj.html
semigroups-3.0.18/doc/attrinv.xml
semigroups-3.0.18/doc/semitrans.xml
semigroups-3.0.18/doc/chap11.html
semigroups-3.0.18/doc/semiringmat.xml
semigroups-3.0.18/doc/chap8.txt
semigroups-3.0.18/doc/chap0_mj.html
semigroups-3.0.18/doc/bipart.xml
semigroups-3.0.18/doc/chap9.txt
semigroups-3.0.18/doc/chap2.html
semigroups-3.0.18/doc/chap14_mj.html
semigroups-3.0.18/doc/grpffmat.xml
semigroups-3.0.18/doc/ideals.xml
semigroups-3.0.18/doc/maximal.xml
semigroups-3.0.18/doc/semirms.xml
semigroups-3.0.18/doc/semigraph.xml
semigroups-3.0.18/doc/chap3.html
semigroups-3.0.18/doc/chap1_mj.html
semigroups-3.0.18/doc/title.xml
semigroups-3.0.18/doc/chap15_mj.html
semigroups-3.0.18/doc/semiact.xml
semigroups-3.0.18/doc/chap10.html
semigroups-3.0.18/doc/chap8_mj.html
semigroups-3.0.18/doc/boolmat.xml
semigroups-3.0.18/doc/main.xml
semigroups-3.0.18/doc/chapInd.html
semigroups-3.0.18/doc/semifp.xml
semigroups-3.0.18/doc/normalizer.xml
semigroups-3.0.18/doc/z-chap07.xml
semigroups-3.0.18/doc/chap3_mj.html
semigroups-3.0.18/doc/z-chap13.xml
semigroups-3.0.18/doc/conginv.xml
semigroups-3.0.18/doc/congpairs.xml
semigroups-3.0.18/doc/chapInd.txt
semigroups-3.0.18/doc/properties.xml
semigroups-3.0.18/doc/chap13.txt
semigroups-3.0.18/doc/chap12.txt
semigroups-3.0.18/doc/cong.xml
semigroups-3.0.18/doc/chap4.html
semigroups-3.0.18/doc/chap17_mj.html
semigroups-3.0.18/doc/z-chap12.xml
semigroups-3.0.18/doc/z-chap06.xml
semigroups-3.0.18/doc/io.xml
semigroups-3.0.18/doc/z-chap10.xml
semigroups-3.0.18/doc/z-chap04.xml
semigroups-3.0.18/doc/semigroups.xml
semigroups-3.0.18/doc/chap10.txt
semigroups-3.0.18/doc/chap11.txt
semigroups-3.0.18/doc/chap8.html
semigroups-3.0.18/doc/nocolorprompt.css
semigroups-3.0.18/doc/chap17.html
semigroups-3.0.18/doc/z-chap05.xml
semigroups-3.0.18/doc/z-chap11.xml
semigroups-3.0.18/doc/gree.xml
semigroups-3.0.18/doc/chap16.html
semigroups-3.0.18/doc/z-chap15.xml
semigroups-3.0.18/doc/z-chap01.xml
semigroups-3.0.18/doc/maxplusmat.xml
semigroups-3.0.18/doc/lefttoc.css
semigroups-3.0.18/doc/chap9.html
semigroups-3.0.18/doc/factor.xml
semigroups-3.0.18/doc/chap15.txt
semigroups-3.0.18/doc/chap14.txt
semigroups-3.0.18/doc/semiboolmat.xml
semigroups-3.0.18/doc/conguniv.xml
semigroups-3.0.18/doc/old.xml
semigroups-3.0.18/doc/isomorph.xml
semigroups-3.0.18/doc/z-chap14.xml
semigroups-3.0.18/doc/z-chap02.xml
semigroups-3.0.18/doc/z-chap16.xml
semigroups-3.0.18/doc/chap2_mj.html
semigroups-3.0.18/doc/chap5.html
semigroups-3.0.18/doc/chap16.txt
semigroups-3.0.18/doc/chap17.txt
semigroups-3.0.18/doc/semimaxplus.xml
semigroups-3.0.18/doc/z-chap17.xml
semigroups-3.0.18/doc/fropin.xml
semigroups-3.0.18/doc/z-chap03.xml
semigroups-3.0.18/doc/chap16_mj.html
semigroups-3.0.18/doc/chap19.html
semigroups-3.0.18/doc/congrms.xml
semigroups-3.0.18/doc/semigroups.bib
semigroups-3.0.18/doc/chap6.html
semigroups-3.0.18/doc/chap13_mj.html
semigroups-3.0.18/doc/chapBib.txt
semigroups-3.0.18/doc/pbr.xml
semigroups-3.0.18/doc/chap7_mj.html
semigroups-3.0.18/doc/attr.xml
semigroups-3.0.18/doc/chap15.html
semigroups-3.0.18/doc/z-chap19.xml
semigroups-3.0.18/doc/semibipart.xml
semigroups-3.0.18/doc/chap19.txt
semigroups-3.0.18/doc/chap18.txt
semigroups-3.0.18/doc/freeband.xml
semigroups-3.0.18/doc/z-chap18.xml
semigroups-3.0.18/doc/z-chap08.xml
semigroups-3.0.18/doc/semigrp.xml
semigroups-3.0.18/doc/z-chap20.xml
semigroups-3.0.18/doc/display.xml
semigroups-3.0.18/doc/trans.xml
semigroups-3.0.18/doc/semiffmat.xml
semigroups-3.0.18/doc/chap14.html
semigroups-3.0.18/doc/z-chap09.xml
semigroups-3.0.18/doc/chap12_mj.html
semigroups-3.0.18/doc/semipperm.xml
semigroups-3.0.18/doc/freeinverse.xml
semigroups-3.0.18/doc/chap6_mj.html
semigroups-3.0.18/doc/chap7.html
semigroups-3.0.18/doc/chap18.html
semigroups-3.0.18/doc/gren.xml
semigroups-3.0.18/doc/z-chap22.xml
semigroups-3.0.18/doc/chap13.html
semigroups-3.0.18/doc/obsolete.xml
semigroups-3.0.18/doc/times.css
semigroups-3.0.18/doc/acting.xml
semigroups-3.0.18/doc/utils.xml
semigroups-3.0.18/doc/toggless.css
semigroups-3.0.18/doc/chap19_mj.html
semigroups-3.0.18/doc/chap2.txt
semigroups-3.0.18/doc/chap3.txt
semigroups-3.0.18/doc/chapBib.html
semigroups-3.0.18/doc/chap10_mj.html
semigroups-3.0.18/doc/chap0.html
semigroups-3.0.18/doc/chap1.txt
semigroups-3.0.18/doc/conglatt.xml
semigroups-3.0.18/doc/chap0.txt
semigroups-3.0.18/doc/isorms.xml
semigroups-3.0.18/doc/chap4_mj.html
semigroups-3.0.18/doc/grac.xml
semigroups-3.0.18/doc/manual.css
semigroups-3.0.18/doc/chap11_mj.html
semigroups-3.0.18/doc/chap4.txt
semigroups-3.0.18/doc/chap5.txt
semigroups-3.0.18/doc/ragged.css
semigroups-3.0.18/doc/chap1.html
semigroups-3.0.18/doc/semipbr.xml
semigroups-3.0.18/doc/chap5_mj.html
semigroups-3.0.18/doc/semicons.xml
semigroups-3.0.18/doc/chap7.txt
semigroups-3.0.18/doc/chap18_mj.html
semigroups-3.0.18/doc/chap6.txt
semigroups-3.0.18/doc/attract.xml
semigroups-3.0.18/doc/chapInd_mj.html
semigroups-3.0.18/doc/chooser.html
semigroups-3.0.18/doc/elements.xml
semigroups-3.0.18/doc/chap12.html
semigroups-3.0.18/tst/testinstall.tst
semigroups-3.0.18/tst/extreme/semiffmat.tst
semigroups-3.0.18/tst/extreme/semibipart.tst
semigroups-3.0.18/tst/extreme/freeband.tst
semigroups-3.0.18/tst/extreme/monoid_pkg.tst
semigroups-3.0.18/tst/extreme/gracreg.tst
semigroups-3.0.18/tst/extreme/misc.tst
semigroups-3.0.18/tst/extreme/grac.tst
semigroups-3.0.18/tst/extreme/semiiter.tst
semigroups-3.0.18/tst/extreme/README
semigroups-3.0.18/tst/extreme/normalizer.tst
semigroups-3.0.18/tst/extreme/closure.tst
semigroups-3.0.18/tst/extreme/ideals.tst
semigroups-3.0.18/tst/extreme/maximal.tst
semigroups-3.0.18/tst/extreme/semirms.tst
semigroups-3.0.18/tst/extreme/bipart.tst
semigroups-3.0.18/tst/extreme/attrinv.tst
semigroups-3.0.18/tst/extreme/examples.tst
semigroups-3.0.18/tst/extreme/inverse.tst
semigroups-3.0.18/tst/extreme/semigroups.tst
semigroups-3.0.18/tst/extreme/properties.tst
semigroups-3.0.18/tst/extreme/conginv.tst
semigroups-3.0.18/tst/extreme/cong.tst
semigroups-3.0.18/tst/extreme/transform.tst
semigroups-3.0.18/tst/workspaces/load-workspace.tst
semigroups-3.0.18/tst/workspaces/save-workspace.tst
semigroups-3.0.18/tst/standard/options.tst
semigroups-3.0.18/tst/standard/semipperm.tst
semigroups-3.0.18/tst/standard/gracinv.tst
semigroups-3.0.18/tst/standard/setup.tst
semigroups-3.0.18/tst/standard/gren.tst
semigroups-3.0.18/tst/standard/freeinverse.tst
semigroups-3.0.18/tst/standard/display.tst
semigroups-3.0.18/tst/standard/trans.tst
semigroups-3.0.18/tst/standard/semigrp.tst
semigroups-3.0.18/tst/standard/semiffmat.tst
semigroups-3.0.18/tst/standard/semiquo.tst
semigroups-3.0.18/tst/standard/semibipart.tst
semigroups-3.0.18/tst/standard/freeband.tst
semigroups-3.0.18/tst/standard/pbr.tst
semigroups-3.0.18/tst/standard/congrms.tst
semigroups-3.0.18/tst/standard/congfpmon.tst
semigroups-3.0.18/tst/standard/attr.tst
semigroups-3.0.18/tst/standard/idealact.tst
semigroups-3.0.18/tst/standard/elements.tst
semigroups-3.0.18/tst/standard/attract.tst
semigroups-3.0.18/tst/standard/gracreg.tst
semigroups-3.0.18/tst/standard/semipbr.tst
semigroups-3.0.18/tst/standard/semicons.tst
semigroups-3.0.18/tst/standard/conglatt.tst
semigroups-3.0.18/tst/standard/grac.tst
semigroups-3.0.18/tst/standard/isorms.tst
semigroups-3.0.18/tst/standard/obsolete.tst
semigroups-3.0.18/tst/standard/acting.tst
semigroups-3.0.18/tst/standard/congsimple.tst
semigroups-3.0.18/tst/standard/README
semigroups-3.0.18/tst/standard/boolmat.tst
semigroups-3.0.18/tst/standard/uf.tst
semigroups-3.0.18/tst/standard/normalizer.tst
semigroups-3.0.18/tst/standard/semifp.tst
semigroups-3.0.18/tst/standard/semigraph.tst
semigroups-3.0.18/tst/standard/semiact.tst
semigroups-3.0.18/tst/standard/semiringmat.tst
semigroups-3.0.18/tst/standard/grpffmat.tst
semigroups-3.0.18/tst/standard/ideals.tst
semigroups-3.0.18/tst/standard/maximal.tst
semigroups-3.0.18/tst/standard/pperm.tst
semigroups-3.0.18/tst/standard/idealenum.tst
semigroups-3.0.18/tst/standard/semirms.tst
semigroups-3.0.18/tst/standard/bipart.tst
semigroups-3.0.18/tst/standard/ffmat.tst
semigroups-3.0.18/tst/standard/congrees.tst
semigroups-3.0.18/tst/standard/semiex.tst
semigroups-3.0.18/tst/standard/blocks.tst
semigroups-3.0.18/tst/standard/attrinv.tst
semigroups-3.0.18/tst/standard/semitrans.tst
semigroups-3.0.18/tst/standard/grpperm.tst
semigroups-3.0.18/tst/standard/semimaxplus.tst
semigroups-3.0.18/tst/standard/fropin.tst
semigroups-3.0.18/tst/standard/factor.tst
semigroups-3.0.18/tst/standard/gree.tst
semigroups-3.0.18/tst/standard/maxplusmat.tst
semigroups-3.0.18/tst/standard/isomorph.tst
semigroups-3.0.18/tst/standard/semiboolmat.tst
semigroups-3.0.18/tst/standard/conguniv.tst
semigroups-3.0.18/tst/standard/congpairs.tst
semigroups-3.0.18/tst/standard/properties.tst
semigroups-3.0.18/tst/standard/conginv.tst
semigroups-3.0.18/tst/standard/io.tst
semigroups-3.0.18/tst/standard/cong.tst
semigroups-3.0.18/src/bipart.cc
semigroups-3.0.18/src/pkg.h
semigroups-3.0.18/src/congpairs.h
semigroups-3.0.18/src/pkg.cc
semigroups-3.0.18/src/converter.h
semigroups-3.0.18/src/semigroups-debug.h
semigroups-3.0.18/src/rnams.h
semigroups-3.0.18/src/semigrp.h
semigroups-3.0.18/src/semigrp.cc
semigroups-3.0.18/src/fropin.h
semigroups-3.0.18/src/congpairs.cc
semigroups-3.0.18/src/.clang-format
semigroups-3.0.18/src/converter.cc
semigroups-3.0.18/src/semigroups-config.h
semigroups-3.0.18/src/CPPLINT.cfg
semigroups-3.0.18/src/bipart.h
semigroups-3.0.18/src/uf.h
semigroups-3.0.18/src/fropin.cc
semigroups-3.0.18/src/uf.cc
semigroups-3.0.18/src/libsemigroups/configure.ac
semigroups-3.0.18/src/libsemigroups/LICENSE
semigroups-3.0.18/src/libsemigroups/configure
semigroups-3.0.18/src/libsemigroups/Makefile.am
semigroups-3.0.18/src/libsemigroups/README.md
semigroups-3.0.18/src/libsemigroups/VERSION
semigroups-3.0.18/src/libsemigroups/.clang-format
semigroups-3.0.18/src/libsemigroups/CPPLINT.cfg
semigroups-3.0.18/src/libsemigroups/Doxyfile
semigroups-3.0.18/src/libsemigroups/Makefile.in
semigroups-3.0.18/src/libsemigroups/aclocal.m4
semigroups-3.0.18/src/libsemigroups/autom4te.cache/traces.0
semigroups-3.0.18/src/libsemigroups/autom4te.cache/traces.1
semigroups-3.0.18/src/libsemigroups/autom4te.cache/output.0
semigroups-3.0.18/src/libsemigroups/autom4te.cache/output.1
semigroups-3.0.18/src/libsemigroups/autom4te.cache/requests
semigroups-3.0.18/src/libsemigroups/config/install-sh
semigroups-3.0.18/src/libsemigroups/config/ltmain.sh
semigroups-3.0.18/src/libsemigroups/config/ar-lib
semigroups-3.0.18/src/libsemigroups/config/config.h.in
semigroups-3.0.18/src/libsemigroups/config/config.guess
semigroups-3.0.18/src/libsemigroups/config/depcomp
semigroups-3.0.18/src/libsemigroups/config/missing
semigroups-3.0.18/src/libsemigroups/config/config.sub
semigroups-3.0.18/src/libsemigroups/config/compile
semigroups-3.0.18/src/libsemigroups/config/config.h.in~
semigroups-3.0.18/src/libsemigroups/tests/partition.test.cc
semigroups-3.0.18/src/libsemigroups/tests/kbp.test.cc
semigroups-3.0.18/src/libsemigroups/tests/rwse.test.cc
semigroups-3.0.18/src/libsemigroups/tests/catch.hpp
semigroups-3.0.18/src/libsemigroups/tests/rws.test.cc
semigroups-3.0.18/src/libsemigroups/tests/uf.test.cc
semigroups-3.0.18/src/libsemigroups/tests/timer.test.cc
semigroups-3.0.18/src/libsemigroups/tests/semiring.test.cc
semigroups-3.0.18/src/libsemigroups/tests/blocks.test.cc
semigroups-3.0.18/src/libsemigroups/tests/semigroups.test.cc
semigroups-3.0.18/src/libsemigroups/tests/kbfp.test.cc
semigroups-3.0.18/src/libsemigroups/tests/recvec.test.cc
semigroups-3.0.18/src/libsemigroups/tests/elements.test.cc
semigroups-3.0.18/src/libsemigroups/tests/cong.test.cc
semigroups-3.0.18/src/libsemigroups/tests/p.test.cc
semigroups-3.0.18/src/libsemigroups/tests/tc.test.cc
semigroups-3.0.18/src/libsemigroups/tests/main.test.cc
semigroups-3.0.18/src/libsemigroups/m4/ltversion.m4
semigroups-3.0.18/src/libsemigroups/m4/._ltsugar.m4
semigroups-3.0.18/src/libsemigroups/m4/libtool.m4
semigroups-3.0.18/src/libsemigroups/m4/ltoptions.m4
semigroups-3.0.18/src/libsemigroups/m4/ltsugar.m4
semigroups-3.0.18/src/libsemigroups/m4/m4_ax_cxx_compile_stdcxx_11.m4
semigroups-3.0.18/src/libsemigroups/m4/m4_ax_cxx_compile_stdcxx.m4
semigroups-3.0.18/src/libsemigroups/m4/._lt~obsolete.m4
semigroups-3.0.18/src/libsemigroups/m4/m4_ax_code_coverage.m4
semigroups-3.0.18/src/libsemigroups/m4/ax_pthread.m4
semigroups-3.0.18/src/libsemigroups/m4/._ltoptions.m4
semigroups-3.0.18/src/libsemigroups/m4/lt~obsolete.m4
semigroups-3.0.18/src/libsemigroups/m4/ax_prefix_config_h.m4
semigroups-3.0.18/src/libsemigroups/src/blocks.cc
semigroups-3.0.18/src/libsemigroups/src/semigroups.cc
semigroups-3.0.18/src/libsemigroups/src/elements.h
semigroups-3.0.18/src/libsemigroups/src/libsemigroups-debug.h
semigroups-3.0.18/src/libsemigroups/src/rwse.cc
semigroups-3.0.18/src/libsemigroups/src/semigroups.h
semigroups-3.0.18/src/libsemigroups/src/rwse.h
semigroups-3.0.18/src/libsemigroups/src/semiring.h
semigroups-3.0.18/src/libsemigroups/src/blocks.h
semigroups-3.0.18/src/libsemigroups/src/timer.h
semigroups-3.0.18/src/libsemigroups/src/recvec.h
semigroups-3.0.18/src/libsemigroups/src/cong.h
semigroups-3.0.18/src/libsemigroups/src/elements.cc
semigroups-3.0.18/src/libsemigroups/src/report.h
semigroups-3.0.18/src/libsemigroups/src/partition.h
semigroups-3.0.18/src/libsemigroups/src/cong.cc
semigroups-3.0.18/src/libsemigroups/src/rws.h
semigroups-3.0.18/src/libsemigroups/src/uf.h
semigroups-3.0.18/src/libsemigroups/src/rws.cc
semigroups-3.0.18/src/libsemigroups/src/uf.cc
semigroups-3.0.18/src/libsemigroups/src/cong/kbp.cc
semigroups-3.0.18/src/libsemigroups/src/cong/tc.h
semigroups-3.0.18/src/libsemigroups/src/cong/p.cc
semigroups-3.0.18/src/libsemigroups/src/cong/p.h
semigroups-3.0.18/src/libsemigroups/src/cong/kbfp.h
semigroups-3.0.18/src/libsemigroups/src/cong/tc.cc
semigroups-3.0.18/src/libsemigroups/src/cong/kbp.h
semigroups-3.0.18/src/libsemigroups/src/cong/kbfp.cc

=====================end of the list of text files=======
=====================binary files========================
semigroups-3.0.18/configure.ac
semigroups-3.0.18/configure
semigroups-3.0.18/CHANGELOG.md
semigroups-3.0.18/VERSIONS
semigroups-3.0.18/.gaplint.yml
semigroups-3.0.18/Makefile.am
semigroups-3.0.18/CONTRIBUTING.md
semigroups-3.0.18/.mailmap
semigroups-3.0.18/Makefile.in
semigroups-3.0.18/aclocal.m4
semigroups-3.0.18/autogen.sh
semigroups-3.0.18/.LIBSEMIGROUPS_VERSION
semigroups-3.0.18/cnf/install-sh
semigroups-3.0.18/cnf/ltmain.sh
semigroups-3.0.18/cnf/ar-lib
semigroups-3.0.18/cnf/pkgconfig.h.in~
semigroups-3.0.18/cnf/config.guess
semigroups-3.0.18/cnf/depcomp
semigroups-3.0.18/cnf/missing
semigroups-3.0.18/cnf/config.sub
semigroups-3.0.18/cnf/compile
semigroups-3.0.18/cnf/pkgconfig.h.in
semigroups-3.0.18/m4/ltversion.m4
semigroups-3.0.18/m4/libtool.m4
semigroups-3.0.18/m4/ltoptions.m4
semigroups-3.0.18/m4/ac_find_gap.m4
semigroups-3.0.18/m4/ltsugar.m4
semigroups-3.0.18/m4/ax_compare_version.m4
semigroups-3.0.18/m4/m4_ax_cxx_compile_stdcxx_11.m4
semigroups-3.0.18/m4/m4_ax_cxx_compile_stdcxx.m4
semigroups-3.0.18/m4/ax_pthread.m4
semigroups-3.0.18/m4/lt~obsolete.m4
semigroups-3.0.18/m4/ax_prefix_config_h.m4
semigroups-3.0.18/doc/manual.six
semigroups-3.0.18/doc/manual.js
semigroups-3.0.18/doc/rainbow.js
semigroups-3.0.18/doc/manual.pdf
semigroups-3.0.18/doc/toggless.js
semigroups-3.0.18/data/doc/greens.pickle
semigroups-3.0.18/data/tst/testdata
semigroups-3.0.18/data/tst/pperm10
semigroups-3.0.18/data/tst/testinstall.pickle
semigroups-3.0.18/data/tst/trans3
semigroups-3.0.18/data/tst/bipart4
semigroups-3.0.18/data/gens/fullbool.pickle.gz
semigroups-3.0.18/data/gens/reflex.pickle.gz
semigroups-3.0.18/data/gens/hall.pickle.gz

=====================end of the list of binary files=====
```

**Comment by alex-konovalov** [comment]
More good news @james-d-mitchell @wilfwilson - Semigroups tests now pass at https://travis-ci.org/gap-system/gap-docker-pkg-tests-master-staging/jobs/428099212

**Comment by james-d-mitchell** [comment]
Great! thanks

**Pull request merged**
