### PR TITLE
Add EvaluateExtRepObjWord change EvaluateWord

### PR DESCRIPTION
**Pull request by ChristopherRussell**
Added new method `EvaluateExtRepObjWord` to help when dealing with ExtRep objects. Reduced the three methods for `EvaluateWord` to two methods that have less restrictive filters.

EDIT: I still need to add documentation and tests

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
You can leave the PR open when you're adding tests and doc.

**Comment by james-d-mitchell** [comment]
Nice one, looks good to me.

**Comment by james-d-mitchell** [comment]
Some tests would be nice, I'm not completely sure that doc is required, since there wasn't any before :)

**Comment by james-d-mitchell** [comment]
Any comments @wilfwilson or @mtorpey ?

**Comment by ChristopherRussell** [comment]
Regarding documentation, if we have an fp semigroup `F` and an element `x` then

`EvaluateExtRepObjWord(Generators(F), ExtRepOfObj(x)) = x`

will return true. However `ExtRepOfObj` has different implementations for different types of semigroups and sometimes no implementation. Furthermore the implementation for finitely presented semigroups is not documented.

**Comment by james-d-mitchell** [comment]
Ok, I don't really see any of that as a problem, if you want please add doc.

**Comment by james-d-mitchell** [comment]
@ChristopherRussell I'm happy with this, but since I merged your last PR, you'll have to rebase this one onto `stable-3.0` again.

**Comment by ChristopherRussell** [comment]
@james-d-mitchell thanks. I have just rebased now.

**Pull request merged**
