### PR TITLE
Update Wilf's details in PackageInfo.g

### PR DESCRIPTION
**Pull request by wilfwilson**
Since I'm at a different university now, I thought it made sense to adjust my details in `PackageInfo.g`.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
Looks like travis failed on this, any comments as to why??

**Comment by wilfwilson** [comment]
For the last day or two, the Travis tests in the Semigroups package against the master branch of GAP failed. I made an issue about this here: https://github.com/gap-packages/Semigroups/issues/522. It was not our fault, but was a result of fixes made to GAP which meant that certain filters had different ranks, and so the methods that we expected to be run (and were testing for) weren't necessarily those that were being tested.

It took me most of yesterday to get this fixed. Fixing the Travis tests also required a PR to GAP master, so I merged some stuff while the tests were still failing, if it was obvious to me what the failures were, to speed up the process. The changes I made in this PR were not the cause of the test failures.

All tests are passing now in `master` and `stable-3.0` branches!

**Comment by alex-konovalov** [comment]
Are you making new Semigroups release now?

**Comment by james-d-mitchell** [comment]
Will do

**Pull request merged**
